# Generated by Django 4.1.13 on 2024-03-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member_1st',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Member_2nd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.team')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceModel',
        ),
        migrations.AddField(
            model_name='member_2nd',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.team'),
        ),
        migrations.AddField(
            model_name='member_1st',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.team'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.team'),
        ),
    ]
