# Generated by Django 4.1.13 on 2024-03-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_member_1st_member_2nd_team_teamleader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_1st',
            name='team',
        ),
        migrations.RemoveField(
            model_name='member_2nd',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='team',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Member_1st',
        ),
        migrations.DeleteModel(
            name='Member_2nd',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamLeader',
        ),
    ]
